Re-enable media plugins & call older API on Linux
Errors complaining that there are no such file or directory:
 #include "cef/dullahan_version.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~
 #include "vlc/libvlc_version.h"
          ^~~~~~~~~~~~~~~~~~~~~~
indicates that CEF & libvlc had somehow been excluded on Linux.

After re-enabling them again, this error would show up.

no matching function for call to ‘dullahan::setOnCustomSchemeURLCallback(std::_Bind_helper<false, void (MediaPluginCEF::*)(std::basic_string<char>, bool, bool), MediaPluginCEF*, const std::_Placeholder<1>&, const std::_Placeholder<2>&, const std::_Placeholder<3>&>::type)’
                 mCEFLib->setOnCustomSchemeURLCallback(std::bind(&MediaPluginCEF::onCustomSchemeURLCallback, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3));
                                                                                                                                                                                       ^
dullahan.h:342:14: note: candidate: void dullahan::setOnCustomSchemeURLCallback(std::function<void(std::basic_string<char>)>)
         void setOnCustomSchemeURLCallback(std::function<void(const std::string url)> callback);
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
dullahan.h:342:14: note:   no known conversion for argument 1 from ‘std::_Bind_helper<false, void (MediaPluginCEF::*)(std::basic_string<char>, bool, bool), MediaPluginCEF*, const std::_Placeholder<1>&, const std::_Placeholder<2>&, const std::_Placeholder<3>&>::type {aka std::_Bind<void (MediaPluginCEF::*(MediaPluginCEF*, std::_Placeholder<1>, std::_Placeholder<2>, std::_Placeholder<3>))(std::basic_string<char>, bool, bool)>}’ to ‘std::function<void(std::basic_string<char>)>’

The callback function expects 3 parameters now. Turns out it's a
difference of API between Dullahan 1.12.2 and 1.12.4.

This commit is a temporary fix, until we get a Dullahan 1.12.4 that's
working on Linux.