OggVorbis upgraded, recompiled PIC, link reordered
At first there were these:

libogg.a(framing.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIC
libvorbis.a(block.o): relocation R_X86_64_32S against symbol `_floor_P' can not be used when making a PIE object; recompile with -fPIC
libvorbis.a(info.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
libvorbis.a(sharedbook.o): relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIC
libvorbis.a(res0.o): relocation R_X86_64_32 against symbol `vorbis_book_decodevs_add' can not be used when making a PIE object; recompile with -fPIC
libvorbis.a(mapping0.o): relocation R_X86_64_32S against symbol `_floor_P' can not be used when making a PIE object; recompile with -fPIC
libvorbisenc.a(vorbisenc.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
libvorbisfile.a(vorbisfile.o): relocation R_X86_64_32S against symbol `fread@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIC

and then even with PIC compiled, there were these:

block.c:95: undefined reference to `oggpack_writeinit'
block.c:157: undefined reference to `oggpack_writeclear'
analysis.c:40: undefined reference to `oggpack_reset'
analysis.c:55: undefined reference to `oggpack_get_buffer'
analysis.c:56: undefined reference to `oggpack_bytes'
info.c:40: undefined reference to `oggpack_write'
info.c:349: undefined reference to `oggpack_readinit'
info.c:46: undefined reference to `oggpack_read'
info.c:244: undefined reference to `oggpack_bytes'
codebook.c:298: undefined reference to `oggpack_look'
codebook.c:306: undefined reference to `oggpack_adv'
bitrate.c:175: undefined reference to `oggpack_writetrunc'
bitrate.c:242: undefined reference to `oggpack_get_buffer'
vorbisfile.c:439: undefined reference to `vorbis_packet_blocksize'
vorbisfile.c:692: undefined reference to `vorbis_synthesis_halfrate_p'
vorbisfile.c:705: undefined reference to `vorbis_synthesis'
vorbisfile.c:1704: undefined reference to `vorbis_synthesis_trackonly'
vorbisfile.c:1040: undefined reference to `vorbis_synthesis_halfrate'

vorbisenc & vorbisfile depends on vorbis, and vorbis depends on ogg,
hence the new link order.