Remove residue of std=gnu++11 from CEFPlugin.cmake
Errors like these:

lldefs.h:207:45:
error: ‘llmin’ function uses ‘auto’ type specifier without trailing return type
 inline auto llmin(T1 d1, T2 d2, T3 d3, T4 d4)
                                             ^
llstring.h:580:49:
error: ‘utf16str_to_wstring’ function uses ‘auto’ type specifier without trailing return type
 inline auto longname(const INSTR& in, size_t len) \
                                                 ^

note: deduced return type only available with -std=c++14 or -std=gnu++14

may appear and these files are referenced from media_plugin_cef.cpp.

It's very likely to be caused by the C++11 setting from the past.
On some build envs, it didn't seem to hurt, but apparently on some
others, it did. It's not relevant now anyway, and keeping it might
actually bring a problem.