README.md update, especially the Linux section
The change was made by replacing the contents up to just before the
Windows section, with the contents of READMEUbuntuBumpTo18-04-Rev1.txt
which was drafted by Mr. Nicky Perian.

The further changes made were additions to the autobuild configure line,
which are some USE_ prefixes and the OpenGL preference explicit setting
that would be useful to fix the linking error:

/usr/bin/ld: ../llrender/libllrender.a(llimagegl.cpp.o):
undefined reference to symbol 'glGetCompressedTexImageARB'
/usr/lib/x86_64-linux-gnu/libGL.so.1:
error adding symbols: DSO missing from command line

since the newer glvnd doesn't seem to implement that function which
llrender still needs.

Apart from these are that the Kokua repo being mentioned is now kokua
instead of kokua-release, and then also some tidying up.