Fix llphysicsextension_stub installable URL
ERROR: Package not installable due to conflicts
llphysicsextensions_stub
  configuration ReleaseNoQt
  version       4.7.1
  build_id      201506082044

It was referring to a different package, which was Qt WebKit.