JsonCpp recompiled with -fPIC *and* C++11 ABI off
At first there were these:

libjson_linux-gcc-4.6_libmt.a(json_reader.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
libjson_linux-gcc-4.6_libmt.a(json_value.o): relocation R_X86_64_32S against symbol `_ZTVN4Json14ValueAllocatorE' can not be used when making a PIE object; recompile with -fPIC
libjson_linux-gcc-4.6_libmt.a(json_writer.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC

and then even with PIC compiled, there were these:

llsdjson.cpp:57: undefined reference to `Json::Value::asString() const'
llsdjson.cpp:103: undefined reference to `Json::Value::Value(std::string const&)'
llsdjson.cpp:109: undefined reference to `Json::Value::operator[](std::string const&)'
lltranslate.cpp:372: undefined reference to `Json::Value::asString() const'
lltranslate.cpp:332: undefined reference to `Json::Reader::parse(std::string const&, Json::Value&, bool)'
lltranslate.cpp:334: undefined reference to `Json::Reader::getFormatedErrorMessages() const'
llcorehttputil.cpp:841: undefined reference to `Json::FastWriter::write(Json::Value const&)'

And this time it isn't some wrong linking order.
If that old version of JsonCpp is not compiled with the
_GLIBCXX_USE_CXX_ABI macro set to off, then the resulting binaries would
contain std::__cxx11::string as return types to methods like
Json::Value::asString(), which is *different* from the expected
std::string. You could check it by executing something like

strings libjson_linux-gcc-7_libmt.a | grep asString

Yes, this is very likely to be caused by the default setting of the GCC
that came with the build environment being used.