Comment out sampleReflectionProbesLegacy redeclaration
which isn't used anyway in that file, and differs in parameter
qualifiers, which caused a crash (only) on Ubuntu 24.x, with errors:

Fragment info
-------------
0(857) : error c1106: overloaded function declaration "samplereflectionprobeslegacy" differs only in parameter qualifiers

2025-03-09T07:51:26Z WARNING # llrender/llglslshader.cpp(513) createShader : Failed to link shader: Water Shader
2025-03-09T07:51:26Z WARNING # llrender/llglslshader.cpp(518) createShader : Failed to link using shader level 3 trying again using shader level 2

Vertex info
-----------
0(107) : error C3002: call to undefined function "void calcAtmospherics(vec3);"