Link fontconfig, even though not headless on Linux
in order to get rid of this:

/usr/bin/x86_64-linux-gnu-ld: ../llwindow/libllwindow.a(llwindowsdl.cpp.o): undefined reference to symbol 'FcInit'
/usr/lib/x86_64-linux-gnu/libfontconfig.so.1: error adding symbols: DSO missing from command line